Repository VanshKing30/FoodiesWeb, pull requests merged in 2024-07, with the labels that each got.

#388 Added BEM Naming convention
  src/App.css
  src/components/Feedback.jsx
  src/index.css
  src/pages/MenuPage.jsx
Labels: gssoc, level2

#394 Feat:Logout Button Not Working It is just Redirecting #371
  src/App.css
  src/components/Navbar.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level2

#395 Feat:Want to Update Ui Foodlist page as Cards #372
  src/components/FoodCard.jsx
  src/components/Navbar.jsx
  src/pages/Foodlist.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level1

#397 Feat:Allow Canteen Admins to Update food item Images and Description #379
  server/controllers/canteenController.js
  server/routes/canteen.js
  src/components/Modal-update.js
  src/components/Navbar.jsx
  src/pages/Foodlist.jsx
Labels: gssoc, level3

#403 Solved issue 390
  src/pages/Login.jsx
  src/pages/News.jsx
Labels: gssoc, level1

#405 Fixed Design issues with dark mode and add dish page
  src/pages/AddFoodItem.jsx
  src/pages/EditProfile.jsx
  src/pages/Foodlist.jsx
  src/pages/Rateus.jsx
Labels: gssoc, level2

#406 Solved issue 393
  src/pages/AddFoodItem.jsx
  src/pages/EditProfile.jsx
  src/pages/SectionPage.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2

#410 Feat:Want to fix UI of Add Product Page #396
  src/pages/AddFoodItem.jsx
  src/pages/SectionPage.jsx
Labels: gssoc, level2

#411 Feat:Want to Update Canteen Cards #398
  src/components/CanteenCard.jsx
  src/components/CanteenList.jsx
Labels: gssoc, level1

#423 appropriate meta tags are added
  public/index.html
Labels: gssoc, level2

#424 Fix invalid href attributes
  src/components/CanteenCard.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  tailwind.config.js
Labels: gssoc, level1

#425 Add frontend and backend support for canteen social media links
  server/controllers/canteenController.js
  server/models/canteenLoginInfo.js
  server/routes/canteen.js
  src/components/AddSocialMediaModal.jsx
  src/pages/EditProfile.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/SectionPage.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2

#427 Resolved Food item card issue
  src/pages/AddFoodItem.jsx
Labels: gssoc, level1

#428 Contact page added in the footer
  src/components/Footer.jsx
Labels: gssoc, level1

#436 Feat:Want to Write Backend Of FeedBack Page Of Canteens #421
  public/index.html
  server/controllers/feedbackController.js
  server/models/studentfeeback.js
  server/routes/student.js
  src/pages/Login.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level1

#439 Feat:Create News Cards #422
  src/App.js
  src/assets/news1.jpeg
  src/assets/news1.jpg
  src/assets/news2.jpg
  src/assets/news3.jpeg
  src/components/Blog/newss.css
  src/components/Blog/newss.jsx
Labels: gssoc, level1

#441 Feat : contributors page e2e
  envexample
  package.json
  public/index.html
  server/envexample
  src/App.js
  src/components/Navbar.jsx
  src/pages/AddFoodItem.jsx
  src/pages/Contributors.js
  src/pages/Home.jsx
Labels: gssoc, level2

#445 Added the contributors page
  src/App.js
  src/components/Footer.jsx
  src/pages/Contributors.jsx
Labels: gssoc, level2

#449 Feat:Error in updating Food items from Canteen End + This should be in Cards #434
  src/components/Modal-update.js
  src/pages/Foodlist.jsx
Labels: gssoc, level2

#452 Feature/add contact info canteen page
  server/controllers/canteenController.js
  server/models/canteenLoginInfo.js
  server/routes/student.js
  src/pages/EditProfile.jsx
  src/pages/Login.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level2

#453 solved issue 431
  src/App.js
  src/components/Footer.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level1

#458 Update feedbackController.js
  server/controllers/feedbackController.js
Labels: good first issue, gssoc, level1

#460 Create config.js
  src/config.js
Labels: good first issue, gssoc, level1

#454 BugFix for Password overwriting
  src/App.css
Labels: gssoc, level1, ui

#455 solved password icon toggle functionality bug
  src/pages/Signup.jsx
Labels: gssoc, level2

#462 Update index.css
  src/index.css
Labels: good first issue, gssoc, level1

#463 Validate and Alert Users for Empty Form Submissions
  src/pages/ContactUs.jsx
Labels: gssoc, level2

#464 Feat:Canteen Should able to see Feedback Given to Them by User (UI +Integration) #448
  server/controllers/feedbackController.js
  server/routes/student.js
  src/pages/FeedbackList.jsx
  src/pages/SectionPage.jsx
Labels: gssoc, level2

#468 Create errorHandlers.js
  server/routes/errorHandlers.js
Labels: good first issue, gssoc, level1

#473 Bug in Name Section of Sign Up Page is solved
  src/pages/Signup.jsx
Labels: gssoc, level1
