Repository VanshKing30/FoodiesWeb, pull requests merged in 2024-08, with the labels that each got.

#475 Added env.example File for Environment Variable Configuration
  README.md
  server/.env.example
  server/routes/errorHandlers.js
Labels: gssoc, level1

#485 Feat:Want to Write Backend of Contact Us Form #480
  server/controllers/Auth.js
  server/env-example
  server/models/Contact.js
  server/routes/contactRoutes.js
  server/routes/student.js
  src/pages/ContactUs.jsx
Labels: gssoc, level2

#486 Feat:Want to Add Skeletons In all the Cards #479
  src/components/CanteenCardSkeleton.jsx
  src/components/CanteenList.jsx
Labels: gssoc, level1, ui

#490 Feat:Canteen profile is not Editable #487
  src/pages/EditProfile.jsx
Labels: gssoc, level2

#491 Enhanced The UI of the contributions page
  src/pages/Contributors.js
Labels: gssoc, level1

#492 I have created the News Section
  package.json
  src/components/Blog/newss.jsx
Labels: gssoc, level1

#495 Update otpController.js
  server/controllers/otpController.js
Labels: gssoc, level1

#513 Login & Sign Up page
  login and sign up Foodie/dist/Screenshot (804).png
  login and sign up Foodie/dist/index.html
  login and sign up Foodie/dist/script.js
  login and sign up Foodie/dist/style.css
Labels: gssoc, level2

#504 Create EventCard.jsx
  src/components/EventCard.jsx
Labels: gssoc, level1

#505 Create NotificationBell.jsx
  src/components/NotificationBell.jsx
Labels: gssoc, level1

#506 Create TermsOfService.jsx
  src/pages/TermsOfService.jsx
Labels: gssoc, level2

#507 Solved issue 494
  server/controllers/canteenController.js
  server/models/canteenLoginInfo.js
  server/routes/canteen.js
Labels: gssoc, level2

#508 Solved cors issue in server
  server/server.js
Labels: gssoc, level1

#514 Solved issue 509
  src/components/Blog/newss.jsx
  src/pages/News.jsx
Labels: gssoc, level1

#524 Solved issue 512
  server/controllers/canteenController.js
  server/models/canteenLoginInfo.js
  server/routes/canteen.js
  src/App.js
  src/pages/AddTiming.jsx
  src/pages/EditProfile.jsx
Labels: gssoc, level3
