Repository VanshKing30/FoodiesWeb, pull requests merged in 2024-05, with the labels that each got.

#42 Update README.md
  README.md
Labels: documentation, gssoc'24, level 1

#44 Update README for Improved Contributor Guidelines #21
  README.md
Labels: documentation, good first issue, gssoc'24, level 1

#59 Feat: Strong Password will only be accepted Ref-#37
  package.json
  src/pages/Signup.jsx
Labels: enhancement, gssoc'24, level 2, backend

#65 Create code_of_conduct.md
  code_of_conduct.md
Labels: documentation, gssoc'24, level 1

#52 Update README.md for better understanding
  README.md
Labels: documentation, gssoc'24, level 1

#77 Updated UI:About Us page
  src/pages/About.jsx
Labels: enhancement, gssoc'24, level 1, ui, frontend

#124 Created Contributing.md File
  Create Contributing.md
Labels: documentation, gssoc'24, level 1

#150 Responsive Navbar issue 100
  src/components/Navbar.jsx
Labels: gssoc, level1

#132 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#169 fixed Eye toggling shows Opposite behaviour
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: gssoc, level1

#172 fix-#141: Layout Error in About Page.
  src/pages/About.jsx
Labels: gssoc, level1

#179 Fix canteen info card And Responsiveness Of Breakfast,Lunch and dinner card
  src/components/Modal.jsx
  src/pages/SectionPage.jsx
Labels: gssoc, level2

#180 add ci and cd pipelines
  .dockerignore
  .github/workflows/build.yml
  .github/workflows/deploy_backend.yml
  .github/workflows/deploy_frontend.yml
  Dockerfile
  server/.dockerignore
  server/Dockerfile
  src/pages/Signup.jsx
Labels: level3

#188 added max-width in canteen-cards
  src/components/CanteenCard.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level1

#190 Fixed: Adding sessions to website #73
  server/controllers/Auth.js
  server/models/session.js
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2
