Repository VanshKing30/FoodiesWeb, pull requests merged in 2024-06, with the labels that each got.

#209 Fixed about-page img stretching on window resize
  src/pages/About.jsx
Labels: gssoc, level1, ui

#221 Centering news elements
  src/pages/News.jsx
Labels: gssoc, level1

#220 Create automate bot
  .github/workflows/greetings.yml
Labels: gssoc, level1

#216 Readme files updates
  README.md
  package.json
  server/package.json
  src/pages/Signup.jsx
Labels: gssoc, level1

#222 Create LEARN.md
  LEARN.md
Labels: good first issue, gssoc, level1

#227 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: good first issue, level1

#231 Updated Footer
  src/components/Footer.jsx
Labels: good first issue, gssoc, level1, ui

#228 Solved issue 174
  server/config/database.js
  server/server.js
  src/index.js
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: gssoc, level3

#238 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: gssoc, level1

#240 Light and dark theme
  package.json
  src/App.js
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/pages/About.jsx
  src/pages/Home.jsx
  src/pages/News.jsx
  src/themeContext.js
  tailwind.config.js
Labels: good first issue, gssoc, level1, ui

#243 Fixed the path to About link in the footer
  src/components/Footer.jsx
Labels: good first issue, level1, ui

#241 Auto Commenting when a PR is merged
  .github/workflows/auto-comment-pr-merge.yml
Labels: good first issue, gssoc, level1

#244 Update README.md
  README.md
Labels: good first issue, gssoc, level1

#251 Feat:Want To Add Backend Canteen menu item #232
  server/controllers/Auth.js
  server/middlewares/auth.js
  src/components/ModalForm.jsx
  src/pages/AddFoodItem.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MenuPage.jsx
  src/pages/SectionPage.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2

#254 Aligned heading of News page properly such that "Navbar overlapping heading of News page issue" is Resolved
  src/index.css
Labels: good first issue, gssoc, level1, ui

#258 Redesigned Menu Cards
  server/controllers/Auth.js
  src/pages/MenuPage.jsx
Labels: good first issue, gssoc, level1, ui

#264 fix: greetings workflow access token naming convention
  .github/workflows/greetings.yml
Labels: good first issue, level1

#265 Resolved small bug in SignUp page
  src/pages/Signup.jsx
Labels: good first issue, gssoc, level1

#272 Fixed the signup and login issue #255
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: gssoc, level1

#294 updated footer theme in dark mode
  src/components/Footer.jsx
Labels: good first issue, gssoc, level1, ui

#303 Feat:In canteen The canteen should able to see the items they have added plus they can remove them #252
  server/controllers/canteenController.js
  src/App.css
  src/pages/AddFoodItem.jsx
  src/pages/Foodlist.jsx
  src/pages/Login.jsx
  src/pages/SectionPage.jsx
Labels: gssoc, level2

#297 Solved issue 290
  src/pages/About.jsx
Labels: gssoc, level1

#295 Added floating button to scroll back to top
  src/components/FloatBtn/FloatBtn.css
  src/components/FloatBtn/FloatBtn.jsx
  src/pages/About.jsx
  src/pages/Home.jsx
  src/pages/News.jsx
Labels: good first issue, gssoc, level1, ui

#311 Added the Remember me button in authentication successfully
  src/pages/Login.jsx
Labels: gssoc, level1

#308 [Bug]:"Confirm Password" field added in signup page
  server/controllers/Auth.js
  server/package.json
  src/pages/Signup.jsx
Labels: gssoc, level3

#315 Solved issue 304
  server/controllers/Auth.js
  src/App.js
  src/authContext.js
  src/pages/About.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/News.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2

#313 Feat:In FoodList we Can add option to Edit FoodItem Name for Canteen #310
  server/controllers/canteenController.js
  server/routes/canteen.js
  src/components/Modal-update.js
  src/pages/Foodlist.jsx
Labels: gssoc, level1

#312 Enhanced Header
  src/App.css
  src/components/Navbar.jsx
  src/index.css
Labels: gssoc, level2

#309 update Rate-us and Log-out in navbar
  src/components/Navbar.jsx
  src/pages/Rateus.jsx
Labels: good first issue, gssoc, level1

#298 Populate Restaurant Images
  server/config/database.js
  server/server.js
  src/components/CanteenCard.jsx
  src/components/Footer.jsx
  src/index.js
  src/pages/About.jsx
  src/pages/Home.jsx
  src/pages/Licensing.jsx
  src/pages/Login.jsx
  src/pages/PrivacyPolicy.jsx
  src/pages/Signup.jsx
  src/pages/TermsandConditions.jsx
  src/utils/unsplash.js
Labels: gssoc, level1

#275 Contact us frontend with email functionality
  package.json
  public/c4.png
  public/i9.png
  server/controllers/Auth.js
  server/models/Contact.js
  server/routes/contactRoutes.js
  server/server.js
  src/App.js
  src/components/Navbar.jsx
  src/pages/ContactUs.jsx
  src/pages/Login.jsx
  tailwind.config.js
Labels: gssoc, level3

#326 Fixed conflict markers in Auth.js
  server/controllers/Auth.js
Labels: gssoc, level1

#322 Feat:Error In Seeing Menu From User End #314
  envexample
  server/controllers/Auth.js
  server/envexample
  src/components/CanteenCard.jsx
  src/components/ModalForm.jsx
  src/components/Navbar.jsx
  src/pages/AddFoodItem.jsx
  src/pages/EditProfile.jsx
  src/pages/Foodlist.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MenuPage.jsx
  src/pages/SectionPage.jsx
  src/pages/Signup.jsx
Labels: gssoc, level3

#333 Solved the issue #316 Added My canteen button in navbar
  src/components/Navbar.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2

#335 Feat:Want to Fix Nav Bar #331
  src/components/Navbar.jsx
  src/pages/Signup.jsx
Labels: good first issue, gssoc, level1

#340 Added Toastify Message
  src/pages/Rateus.jsx
Labels: good first issue, gssoc, level1

#348 Solved Bugs related to Authentication
  package.json
  server/controllers/Auth.js
  src/authContext.js
  src/components/Navbar.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: gssoc, level3

#353 Signup Page Visibility
  server/package.json
  src/components/Navbar.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2

#355 feat: Improve ui for the contact page
  src/pages/ContactUs.jsx
Labels: gssoc, level1

#358 BUG:When Someone click on About US He is Getting Looged Out #337
  src/pages/About.jsx
  src/pages/Login.jsx
Labels: gssoc, level1

#360 Feat: Lets Update menu make them using Cards #320
  src/components/FoodCard.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level2

#364 eyeicon-setting-fixed
  src/pages/Signup.jsx
Labels: gssoc, level1

#365 Solved issue 350
  server/controllers/Auth.js
  server/server.js
  src/pages/Login.jsx
Labels: gssoc, level2

#368 update favicon
  public/index.html
  public/new_favicon.png
Labels: gssoc, level1

#369 Feat: routes are Secured in wrong Way And Causing a Lot of problem #356
  server/config/passport.js
  server/controllers/Auth.js
  src/App.js
  src/components/Modal.js
  src/pages/About.jsx
  src/pages/Login.jsx
  src/pages/News.jsx
  src/pages/Signup.jsx
Labels: gssoc, level2

#374 Solved issue 351
  src/pages/AddFoodItem.jsx
  src/pages/Login.jsx
  src/pages/SectionPage.jsx
  src/pages/Signup.jsx
Labels: gssoc, level1

#376 Feat:Add search Bar For Food menupage #361
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MenuPage.jsx
Labels: gssoc, level3

#377 Solved issue 351
  src/pages/AddFoodItem.jsx
  src/pages/SectionPage.jsx
Labels: gssoc, level1

#380 Feat:Canteen Navbar should be Different #357
  src/components/Navbar.jsx
Labels: gssoc, level1

#383 Solved issue 305
  server/controllers/canteenController.js
  src/components/Navbar.jsx
  src/pages/Home.jsx
Labels: gssoc, level1
